USE [master]
GO

/****** Object:  Database [Dashboard]    Script Date: 06/12/2024 12:21:28 PM ******/
CREATE DATABASE [Dashboard]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Dashboard', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Dashboard.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Dashboard_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Dashboard_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Dashboard].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Dashboard] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Dashboard] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Dashboard] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Dashboard] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Dashboard] SET ARITHABORT OFF 
GO

ALTER DATABASE [Dashboard] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Dashboard] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Dashboard] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Dashboard] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Dashboard] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Dashboard] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Dashboard] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Dashboard] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Dashboard] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Dashboard] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Dashboard] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Dashboard] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Dashboard] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Dashboard] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Dashboard] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Dashboard] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Dashboard] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Dashboard] SET RECOVERY FULL 
GO

ALTER DATABASE [Dashboard] SET  MULTI_USER 
GO

ALTER DATABASE [Dashboard] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Dashboard] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Dashboard] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Dashboard] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Dashboard] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Dashboard] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Dashboard] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Dashboard] SET  READ_WRITE 
GO


